#!/usr/bin/env bash

function git-br {
  git branch | grep "\*" | cut -d\  -f2
}

function git-all {
  git add --all && git commit
}

function git-up {
  git push origin $(git-br)
}

function git-down {
  git pull origin $(git-br)
}

