#!/usr/bin/env bash

##########
# This file is intended for custom scripts to run on each terminal session load.
##########

# Import user scripts.
USER_SCRIPTS="$HOME/.bashscripts"
if [[ -e $USER_SCRIPTS ]] && [[ -d $USER_SCRIPTS ]]
then
  pushd $USER_SCRIPTS > /dev/null
  for f in $(/usr/bin/env ls -A1)
  do
    source $USER_SCRIPTS/$f
  done
  popd > /dev/null
fi
unset USER_SCRIPTS

# Fork a specified process and suppress stderr.
function fork {
  $* 2> /dev/null &
}

# Fork a process and ignore SIGHUP.
function nhfork {
  nohup $* > /dev/null 2>&1 &
}

# Extract archive based on extension.
function ex {
  if [[ -f $1 ]]
  then
    case $1 in
      *.7z) 7z x $1 ;;
      *.bz2) bunzip2 $1 ;;
      *.jar) jar -x -f $1 ;;
      *.gz) gunzip $1 ;;
      *.rar) unrar x $1 ;;
      *.tar) tar xf $1 ;;
      *.tar.bz2) tar xjf $1 ;;
      *.tar.gz) tar xzf $1 ;;
      *.tbz2) tar xjf $1 ;;
      *.tgz) tar xzf $1 ;;
      *.Z) uncompress $1 ;;
      *.zip) unzip $1 ;;
      *) echo "\"$1\" cannot be extracted using the ex command." ;;
    esac
  else
    echo "\"$1\" is not a valid file."
  fi
}

